apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
  labels:
    "app.kubernetes.io/managed-by": "Helm"
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "0"
spec:
  channel: v5
  installPlanApproval: Automatic
  name: grafana-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: grafana-operator.v5.8.0