apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: my-operator-group
  namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
    - {{ .Release.Namespace }}
  upgradeStrategy: Default