apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-server
  namespace: {{ .Release.Namespace }}
  labels:
    grafana: "swf.grafana.servers"
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: {{ .Values.grafana.password}}
      admin_user: {{ .Values.grafana.username}}
