kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: grafana-route
  namespace: {{ .Release.Namespace }}
spec:
  to:
    kind: Service
    name: grafana-server-service
    weight: 100
  port:
    targetPort: grafana
  tls:
    termination: edge
  wildcardPolicy: None