apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-server
  namespace: {{ .Release.Namespace }}
spec:
  config:
    auth:
      disable_login_form: 'false'
    log:
      mode: console
    security:
      admin_password: admin
      admin_user: admin
